name: Build

on: 
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-windows:
    name: Build on Windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: microsoft/setup-msbuild@v1.1
    - uses: nuget/setup-nuget@v1
    - name: Restore NuGet packages
      run: nuget restore Poedit.sln
    - name: Build solution
      run: msbuild Poedit.sln /p:configuration=Debug
